---
- name: Update RHEL Hosts
  hosts: "{{ target }}"
  gather_facts: true
  become: true
  
  tasks:
  - name: Update all installed packages
    yum:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes